export const ORDERS = [
  {
    id: 5089,
    customer: "Joseph Wheeler",
    date: "2023-04-06",
    total: 2564,
    method: "CC",
    status: "Pending",
  },
  {
    id: 5082,
    customer: "Jane Smith",
    date: "2023-03-30",
    total: 2500,
    method: "Other",
    status: "Pending",
  },
  {
    id: 5083,
    customer: "Alice Johnson",
    date: "2023-03-24",
    total: 3200,
    method: "CC",
    status: "Completed",
  },
  {
    id: 5084,
    customer: "Bob Brown",
    date: "2023-03-23",
    total: 1800,
    method: "Other",
    status: "Canceled",
  },
  {
    id: 5085,
    customer: "Charlie Davis",
    date: "2023-03-22",
    total: 4000,
    method: "CC",
    status: "Completed",
  },
  {
    id: 5086,
    customer: "Diana Evans",
    date: "2023-03-21",
    total: 2200,
    method: "Other",
    status: "Pending",
  },
  {
    id: 5087,
    customer: "Ethan Foster",
    date: "2023-03-20",
    total: 3000,
    method: "CC",
    status: "Completed",
  },
  {
    id: 5088,
    customer: "Fiona Green",
    date: "2023-03-19",
    total: 2700,
    method: "Other",
    status: "Completed",
  },
  {
    id: 5089,
    customer: "George Hall",
    date: "2023-03-18",
    total: 3500,
    method: "CC",
    status: "Canceled",
  },
  {
    id: 50810,
    customer: "Hannah Ivers",
    date: "2023-03-17",
    total: 1900,
    method: "Other",
    status: "Pending",
  },
  {
    id: 50811,
    customer: "Ian Johnson",
    date: "2023-03-16",
    total: 4500,
    method: "CC",
    status: "Completed",
  },
  {
    id: 50812,
    customer: "Julia Kim",
    date: "2023-03-15",
    total: 2800,
    method: "Other",
    status: "Completed",
  },
  {
    id: 50813,
    customer: "Kevin Lee",
    date: "2023-03-14",
    total: 1600,
    method: "CC",
    status: "Canceled",
  },
  {
    id: 50814,
    customer: "Laura Martinez",
    date: "2023-03-13",
    total: 3300,
    method: "Other",
    status: "Pending",
  },
  {
    id: 50815,
    customer: "Michael Nguyen",
    date: "2023-03-12",
    total: "2100",
    method: "CC",
    status: "Completed",
  },
];

export const TABLE_NAV_ITEMS = [
  {
    label: "All Orders",
    value: "All",
  },
  {
    label: "Completed",
    value: "Completed",
  },
  {
    label: "Canceled",
    value: "Canceled",
  },
];

export const PRODUCT_STATUS = [
  {
    label: "All",
    value: "All",
  },
  {
    label: "Pending",
    value: "Pending",
  },
  {
    label: "Completed",
    value: "Completed",
  },
  {
    label: "Canceled",
    value: "Canceled",
  },
];
